### ISSUE TITLE
Error help (I'm ultra noob btw )

### ISSUE THREAD

**Issue by adidas0** [RogerioBlanco/PixelCanvasBot#126]
Been using it for a few days without a problem, suddenly this happened and it keeps happening each time I retry. I dunno what it means

>> 19:14:43 ->Load cached image
>> 19:14:54 ->### closed ###
>> 19:14:54 ->### closed ###
>> 19:14:54 ->### closed ###
Traceback (most recent call last):
  File "C:\Users\mrtro\PixelCanvasBot\main.py", line 139, in <module>
    main()
  File "C:\Users\mrtro\PixelCanvasBot\main.py", line 134, in main
    run()
  File "C:\Users\mrtro\PixelCanvasBot\main.py", line 124, in run
    bot.run()
  File "C:\Users\mrtro\PixelCanvasBot\src\bot.py", line 44, in run
    self.strategy.apply()
  File "C:\Users\mrtro\PixelCanvasBot\src\strategy.py", line 32, in apply
    self.bot.paint(x, y, color)
  File "C:\Users\mrtro\PixelCanvasBot\src\bot.py", line 51, in paint
    response = self.pixelio.send_pixel(x, y, color)
  File "C:\Users\mrtro\PixelCanvasBot\src\pixelcanvasio.py", line 72, in send_pixel
    raise Exception(I18n.get('Oh no, you are using a proxy'))
Exception: >> 19:14:54 ->Oh no, you are using a proxy

E: I think it's caught on to it I can't draw pixels manually either now

**Comment by Qh0stM4N** [comment]
@adidas0 If the error persists when draw manually, you can turn issue back open.
