### ISSUE TITLE
[Suggestion] Generate fingerprint

### ISSUE THREAD

**Issue by RogerioBlanco** [RogerioBlanco/PixelCanvasBot#16]
Well, I looked the source code of pixelcanvas.io and I see where he make the fingerprint. And it's absolutily arbitrary. As we don't use the browser to put the pixels, we make our fingerprint.

The link of source code: https://github.com/Valve/fingerprintjs2

**Comment by Qh0stM4N** [comment]
Is it possible to do this python console application? Why do try It's work allready.
This is a value that can almost always be changed.
maybe browser extension or teamperMonkey (greaseMonkey) script listen pages request for getting fingerprint. Or easy to use html on javascript tool for example
![image](https://user-images.githubusercontent.com/12828465/28029143-573e3056-659f-11e7-832f-ce80128730a1.png)
Maybe same  page published this repositorys github pages ?

**Comment by RogerioBlanco** [comment]
I think so. I will research to do this.

**Comment by Crashzilla** [comment]
Sorry, but could you tell me how you found the source code? I want to make some customization in the code but without the pixelcanvas code it's kinda hard to do so.

**Comment by RogerioBlanco** [comment]
The client.js is the central code for the pixelcanvas.io . I just reverse-engineered the code.

**Comment by Qh0stM4N** [comment]
@Crashzilla you thing's maniplations for pixelcanvas.io javascript code?

**Comment by Crashzilla** [comment]
Sorry @Qh0stM4N I don't understand your question.

**Comment by Cruel100** [comment]
No @Qh0stM4N. It's another person.

**Comment by Qh0stM4N** [comment]
@Cruel100 I did't understand you :( who is another person ?

**Comment by Fercho5656** [comment]
C:\Users\Fernando\Desktop\PixelCanvasBot-master>python main.py
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from src.bot import Bot
  File "C:\Users\Fernando\Desktop\PixelCanvasBot-master\src\bot.py", line 4, in <module>
    from pixelcanvasio import PixelCanvasIO
ModuleNotFoundError: No module named 'pixelcanvasio'


Why i got this?

**Comment by Qh0stM4N** [comment]
Closed. This bot python based CLI application. Web interface or js based fincerprint generator to many update list. getting fingerprint user script or web page based solutions  will not be a viable solution.
maybe a new repository gh-pages or gits more usefull. Or listening all network request from your operation system ? I think a bot that listens to all network wants and gets fingerprints from here is not safe and will not be an appropriate solution for privacy.
