### ISSUE TITLE
Error on new update

### ISSUE THREAD

**Issue by marcussacana** [RogerioBlanco/PixelCanvasBot#46]
Crash with this log:
```C:\python27\lib\site-packages\urllib3\util\ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
C:\python27\lib\site-packages\urllib3\util\ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    main()
  File "main.py", line 43, in main
    bot.run()
  File "C:\pxcv\src\bot.py", line 24, in run
    self.canvas = self.setup_canvas()
  File "C:\pxcv\src\bot.py", line 76, in setup_canvas
    raw = self.pixelio.download_canvas(center_x, center_y)
  File "C:\pxcv\src\pixelcanvasio.py", line 65, in download_canvas
    return self.get(PixelCanvasIO.URL + 'api/bigchunk/%s.%s.bmp' % (center_x, center_y), stream = True).content
  File "C:\pxcv\src\pixelcanvasio.py", line 33, in get
    return requests.get(url, stream=stream, headers=PixelCanvasIO.HEADER_USER_AGENT, proxies = self.proxy)
  File "C:\python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\python27\lib\site-packages\requests\sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\python27\lib\site-packages\requests\sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "C:\python27\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pixelcanvas.io', port=443): Max retries exceeded with url: /api/bigchunk/-135.-42.bmp (Caused by SSLError(SSLError(1, '_ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
```

**Comment by RogerioBlanco** [comment]
Qual versão do seu python?

**Comment by marcussacana** [comment]
Eita é br, mas bem, 2.7... versão errada? mas a anterior funcionou, ou melhor está funcionando...
![image](https://user-images.githubusercontent.com/10576957/28725169-0db26766-7393-11e7-8876-99910d0016a1.png)

**Comment by RogerioBlanco** [comment]
Hehe, br sim morando em Portugal. Me diz, qual é a versão que está funcionando?

**Comment by marcussacana** [comment]
https://github.com/RogerioBlanco/PixelCanvasBot/tree/23235a2deba3533413c03f99f700689255aa70f3

**Comment by RogerioBlanco** [comment]
Testa com essa branch:
https://github.com/RogerioBlanco/PixelCanvasBot/tree/HTTPS-Patch
Se funcionar me dá o feedback, que eu integro ela.

**Comment by marcussacana** [comment]
funcionou

**Comment by RogerioBlanco** [comment]
Done!
