### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by ZeedyPixel** [RogerioBlanco/PixelCanvasBot#59]
```
C:\Users\pc>python main.py -i draw.png -f 61c7b86bb5507fcb7c7585fcf90a185d
 -x 53 -y 95 --proxy_url proxyip --proxy_auth MyAuthProxy
Load cached image
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 49, in main
    bot.init()
  File "C:\Users\Dantas\src\bot.py", line 24, in init
    self.canvas = self.setup_canvas()
  File "C:\Users\Dantas\src\bot.py", line 79, in setup_canvas
    raw = self.pixelio.download_canvas(center_x, center_y)
  File "C:\Users\Dantas\src\pixelcanvasio.py", line 65, in download_canvas
    return self.get(PixelCanvasIO.URL + 'api/bigchunk/%s.%s.bmp' % (center_x, ce
nter_y), stream = True).content
  File "C:\Users\Dantas\src\pixelcanvasio.py", line 33, in get
    return requests.get(url, stream=stream, headers=PixelCanvasIO.HEADER_USER_AG
ENT, proxies = self.proxy)
  File "C:\Python27\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 303, in get_co
nnection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 197, in proxy_
manager_for
    **proxy_kwargs)
  File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 440, in prox
y_from_url
    return ProxyManager(proxy_url=url, **kw)
  File "C:\Python27\lib\site-packages\urllib3\poolmanager.py", line 385, in __in
it__
    proxy = parse_url(proxy_url)
  File "C:\Python27\lib\site-packages\urllib3\util\url.py", line 199, in parse_u
rl
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: "My proxy_auth"
```
I change the objects of it because I don't want to show, but that's the error when I execute it's correctly

**Comment by RogerioBlanco** [comment]
In the options, you are using:
--proxy_url IP:PORT 
--proxy_auth USER:PASS
?

**Comment by ZeedyPixel** [comment]
Yes, i'm using, I just remove it, for security hehe. But I can send to you in your fb all the code.

**Comment by ZeedyPixel** [comment]
FIXED! I was using the domain that's why, it's just support the ip connection.
